name: Send Matrix Notification

on:
  schedule:
    - cron: '0 14 * * *'   # UTC 14:00 = 北京时间 22:00
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install matrix-commander

      - name: Run Python script
        env:
          MATRIX_HOMESERVER: ${{ secrets.MATRIX_HOMESERVER }}
          MATRIX_USERNAME: ${{ secrets.MATRIX_USERNAME }}
          MATRIX_ACCESS_TOKEN: ${{ secrets.MATRIX_ACCESS_TOKEN }}  # 改用 token
          MATRIX_ROOM_ID: ${{ secrets.MATRIX_ROOM_ID }}
        run: python main.py