name: Nalan Calendar

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        env:
          MATRIX_HOMESERVER: ${{ secrets.MATRIX_HOMESERVER }}
          MATRIX_ACCESS_TOKEN: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          MATRIX_ROOM_ID: ${{ secrets.MATRIX_ROOM_ID }}
        run: python main.py
